openapi: 3.0.3
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'https://api.example.com'
paths:
  /anomalies:
    get:
      summary: Returns a list of anomalies.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array

