# Generated by Django 3.2.5 on 2021-09-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccelerationThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('threshold', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
