# Generated by Django 3.2.5 on 2021-09-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0003_auto_20210907_1723'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accelerationlocation',
            unique_together={('latitude', 'longitude')},
        ),
    ]
